management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    version: '@project.version@'
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    description: '@project.description@'

spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  h2:
    console.enabled: true

    datasource:
      url: jdbc:h2:mem:campinho
      username: sa
      password: password
      driverClassName: org.h2.Driver

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: create
      show-sql: true

